@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.exdrill.cave_enhancements.effect;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;