@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.teamabode.cave_enhancements.common.effect;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;